# Generated by Django 3.0.1 on 2020-01-21 19:22

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scientific_name', models.CharField(max_length=80, verbose_name='الاسم العلمي')),
                ('trade_name', models.CharField(max_length=80, verbose_name='الاسم التجاري')),
                ('alternate1', models.CharField(max_length=80, verbose_name='بديل 1')),
                ('alternate2', models.CharField(max_length=80, verbose_name='بديل 2')),
                ('start_date', models.DateField(default=datetime.date.today, verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('creation_date', models.DateField(auto_now=True)),
                ('last_update_date', models.DateField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicine_created_by', to=settings.AUTH_USER_MODEL)),
                ('last_update_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicine_last_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
