# Generated by Django 3.0.1 on 2020-01-27 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='alternate1',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='بديل 1'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='alternate2',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='بديل 2'),
        ),
    ]
