# Generated by Django 3.0.1 on 2020-02-10 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
        ('custom_user', '0002_auto_20200121_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='clinic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_clinic', to='clinic.Clinic', verbose_name='أسم المستشفي'),
        ),
    ]
