# Generated by Django 3.0.1 on 2020-12-06 10:11

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinic', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Surgery_Master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surgery_name', models.CharField(max_length=80, verbose_name='Sergry Name')),
                ('start_date', models.DateField(default=datetime.date.today, verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('creation_date', models.DateField(auto_now=True)),
                ('last_update_date', models.DateField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surgery_master_created_by', to=settings.AUTH_USER_MODEL)),
                ('last_update_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surgery_master_last_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Surgery_Steps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_name', models.CharField(max_length=80, verbose_name='Step')),
                ('start_date', models.DateField(default=datetime.date.today, verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('creation_date', models.DateField(auto_now=True)),
                ('last_update_date', models.DateField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surgery_patient_created_by', to=settings.AUTH_USER_MODEL)),
                ('last_update_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surgery_patient_updated_by', to=settings.AUTH_USER_MODEL)),
                ('sergry_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surgery.Surgery_Master', verbose_name='Sergry Name')),
            ],
        ),
        migrations.CreateModel(
            name='Surgery_Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(blank=True, max_length=120, null=True, verbose_name='Doctor Name')),
                ('creation_date', models.DateField(auto_now=True)),
                ('last_update_date', models.DateField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surgery_doc_created_by', to=settings.AUTH_USER_MODEL)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.Clinic', verbose_name='Hospital')),
                ('last_update_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='surgery_doc_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Patient_Surgery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surgery_date', models.DateField(default=datetime.date.today, verbose_name='Surgery Date')),
                ('exit_date', models.DateField(default=datetime.date.today, verbose_name='Exit Date')),
                ('case_progress', models.CharField(blank=True, max_length=250, null=True, verbose_name='Progress')),
                ('final_diagnosis', models.CharField(blank=True, max_length=250, null=True, verbose_name='Final Diagnosis')),
                ('recomendations', models.TextField(blank=True, null=True, verbose_name='Recomendations')),
                ('start_date', models.DateField(default=datetime.date.today, verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('creation_date', models.DateField(auto_now=True)),
                ('last_update_date', models.DateField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surgery_steps_created_by', to=settings.AUTH_USER_MODEL)),
                ('last_update_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surgery_steps_updated_by', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patient.Patient', verbose_name='Patient')),
                ('surgery_doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surgery.Surgery_Doctor', verbose_name='Surgery Doctor')),
                ('surgery_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surgery.Surgery_Master', verbose_name='Sergry Name')),
            ],
        ),
        migrations.CreateModel(
            name='After_Surgery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('after_surgery_notes', models.TextField(blank=True, null=True, verbose_name='After Surgery Notes')),
                ('after_surgery_recomendations', models.TextField(blank=True, null=True, verbose_name='After Surgery Recomendations')),
                ('follow_up_date', models.DateField(default=datetime.date.today, verbose_name='Follow Up Date')),
                ('creation_date', models.DateField(auto_now=True)),
                ('last_update_date', models.DateField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='after_surgery_created_by', to=settings.AUTH_USER_MODEL)),
                ('last_update_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='after_surgery_updated_by', to=settings.AUTH_USER_MODEL)),
                ('surgery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='surgery.Patient_Surgery', verbose_name='Surgery')),
            ],
        ),
    ]
