# Generated by Django 3.0.1 on 2020-02-07 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surgery', '0003_auto_20200203_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_surgery',
            name='case_progress',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='تطور الحالة'),
        ),
        migrations.AlterField(
            model_name='patient_surgery',
            name='final_diagnosis',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='التشخيص النهائي'),
        ),
        migrations.AlterField(
            model_name='patient_surgery',
            name='recomendations',
            field=models.TextField(blank=True, null=True, verbose_name='توصيات اخري'),
        ),
    ]
