# Generated by Django 3.0.1 on 2020-02-11 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
        ('surgery', '0005_surgery_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='surgery_doctor',
            name='hospital',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='clinic.Clinic', verbose_name='المستشفي'),
            preserve_default=False,
        ),
    ]
