# Generated by Django 3.0.1 on 2020-02-11 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surgery', '0006_surgery_doctor_hospital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surgery_doctor',
            name='doctor_name',
            field=models.CharField(max_length=120, null=True, verbose_name='اسم الدكتور'),
        ),
    ]
