# Generated by Django 3.0.1 on 2020-02-11 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surgery', '0008_auto_20200211_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_surgery',
            name='surgery_doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surgery.Surgery_Doctor', verbose_name='اسم الجراح'),
        ),
    ]
