# Generated by Django 3.0.1 on 2020-03-13 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0039_auto_20200313_0856'),
        ('surgery', '0009_auto_20200211_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_surgery',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patient.Patient', verbose_name='اسم المريضة'),
        ),
    ]
