# Generated by Django 3.0.1 on 2020-03-18 10:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surgery', '0011_after_surgery'),
    ]

    operations = [
        migrations.AddField(
            model_name='after_surgery',
            name='follow_up_date',
            field=models.DateField(default=datetime.date.today, verbose_name='تاريخ المتابعة'),
        ),
    ]
