# Generated by Django 3.0.1 on 2020-11-15 09:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
        ('patient', '0056_auto_20201115_1153'),
        ('surgery', '0012_after_surgery_follow_up_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='after_surgery',
            name='after_surgery_notes',
            field=models.TextField(blank=True, null=True, verbose_name='After Surgery Notes'),
        ),
        migrations.AlterField(
            model_name='after_surgery',
            name='after_surgery_recomendations',
            field=models.TextField(blank=True, null=True, verbose_name='After Surgery Recomendations'),
        ),
        migrations.AlterField(
            model_name='after_surgery',
            name='follow_up_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Follow Up Date'),
        ),
        migrations.AlterField(
            model_name='after_surgery',
            name='surgery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='surgery.Patient_Surgery', verbose_name='Surgery'),
        ),
        migrations.AlterField(
            model_name='patient_surgery',
            name='case_progress',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Progress'),
        ),
        migrations.AlterField(
            model_name='patient_surgery',
            name='exit_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Exit Date'),
        ),
        migrations.AlterField(
            model_name='patient_surgery',
            name='final_diagnosis',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Final Diagnosis'),
        ),
        migrations.AlterField(
            model_name='patient_surgery',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patient.Patient', verbose_name='Patient'),
        ),
        migrations.AlterField(
            model_name='patient_surgery',
            name='recomendations',
            field=models.TextField(blank=True, null=True, verbose_name='Recomendations'),
        ),
        migrations.AlterField(
            model_name='patient_surgery',
            name='surgery_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Surgery Date'),
        ),
        migrations.AlterField(
            model_name='patient_surgery',
            name='surgery_doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surgery.Surgery_Doctor', verbose_name='Surgery Doctor'),
        ),
        migrations.AlterField(
            model_name='patient_surgery',
            name='surgery_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surgery.Surgery_Master', verbose_name='Sergry Name'),
        ),
        migrations.AlterField(
            model_name='surgery_doctor',
            name='doctor_name',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Doctor Name'),
        ),
        migrations.AlterField(
            model_name='surgery_doctor',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.Clinic', verbose_name='Hospital'),
        ),
        migrations.AlterField(
            model_name='surgery_master',
            name='surgery_name',
            field=models.CharField(max_length=80, verbose_name='Sergry Name'),
        ),
        migrations.AlterField(
            model_name='surgery_steps',
            name='sergry_master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surgery.Surgery_Master', verbose_name='Sergry Name'),
        ),
        migrations.AlterField(
            model_name='surgery_steps',
            name='step_name',
            field=models.CharField(max_length=80, verbose_name='Steps'),
        ),
    ]
