# Generated by Django 3.0.1 on 2020-01-21 19:10

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='الأسم')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='العنوان')),
                ('phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='الهاتف')),
                ('mobile', models.CharField(blank=True, max_length=255, null=True, verbose_name='المحمول')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='تاريخ الميلاد')),
                ('job', models.CharField(max_length=30, verbose_name='الوظيفة')),
                ('insurance_number', models.PositiveIntegerField(verbose_name='الرقم التأميني')),
                ('entrance_number', models.PositiveIntegerField(verbose_name='رقم الدخول')),
                ('hospital_number', models.PositiveIntegerField(verbose_name='رقم المستشفي الموحد')),
                ('patient_number', models.PositiveIntegerField(verbose_name='رقم المريضة')),
                ('room', models.CharField(max_length=70, verbose_name='الغرفة')),
                ('hospital_section', models.CharField(max_length=70, verbose_name='القسم')),
                ('consultant_flag', models.BooleanField(verbose_name='استشاري')),
                ('start_date', models.DateField(default=datetime.date.today, verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('creation_date', models.DateField(auto_now=True)),
                ('last_update_date', models.DateField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_created_by', to=settings.AUTH_USER_MODEL)),
                ('last_update_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_last_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Patient_Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment_name', models.CharField(max_length=150, verbose_name='Attachment Name')),
                ('attachment', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Attachment')),
                ('start_date', models.DateField(default=datetime.date.today, verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('creation_date', models.DateField(auto_now=True)),
                ('last_update_date', models.DateField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_attach_created_by', to=settings.AUTH_USER_MODEL)),
                ('last_update_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_attach_last_updated_by', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patient.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=150, verbose_name='بيانات عن الحمل')),
                ('type', models.CharField(choices=[('n', 'طبيعي'), ('c', 'قيصري')], max_length=30, verbose_name='نوع الولادة')),
                ('place', models.CharField(blank=True, max_length=100, null=True, verbose_name='مكان الولادة')),
                ('date', models.DateField(blank=True, null=True, verbose_name='تاريخ الولادة')),
                ('abo_rh', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=50, null=True, verbose_name='فصيلة الدم')),
                ('fetal_sex', models.CharField(blank=True, choices=[('m', 'ذكر'), ('f', 'انثي')], max_length=50, null=True, verbose_name='نوع المولود')),
                ('lnmp', models.DateField(blank=True, null=True, verbose_name='اخر تاريخ للدورة الشهرية')),
                ('creation_date', models.DateField(auto_now=True)),
                ('last_update_date', models.DateField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_created_by', to=settings.AUTH_USER_MODEL)),
                ('last_update_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_last_updated_by', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patient.Patient', verbose_name='المريضة')),
            ],
        ),
        migrations.CreateModel(
            name='Check_Up',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complain', models.CharField(max_length=70, verbose_name='المتابعة')),
                ('visit_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الزيارة')),
                ('next_visit', models.DateField(blank=True, null=True, verbose_name='تاريخ الزيارة القادم')),
                ('blood_presure', models.CharField(default='120/80', max_length=6, verbose_name='ضغط الدم')),
                ('protine', models.CharField(blank=True, max_length=3, null=True)),
                ('rbs', models.CharField(blank=True, max_length=6, null=True)),
                ('hemoglobin', models.CharField(blank=True, max_length=6, null=True)),
                ('weight', models.PositiveIntegerField(blank=True, null=True)),
                ('start_date', models.DateField(default=datetime.date.today, verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('creation_date', models.DateField(auto_now=True)),
                ('last_update_date', models.DateField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_up_created_by', to=settings.AUTH_USER_MODEL)),
                ('delivery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patient.Delivery', verbose_name='الولادة')),
                ('last_update_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_up_last_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
