# Generated by Django 3.0.1 on 2020-01-21 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_auto_20200121_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='description',
            field=models.TextField(max_length=250, verbose_name='بيانات عن الحمل'),
        ),
    ]
