# Generated by Django 2.2 on 2021-03-08 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_auto_20210306_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='barcode',
            field=models.ImageField(blank=True, null=True, upload_to='barcode/'),
        ),
        migrations.AlterField(
            model_name='past_medical_history',
            name='autoimmun_disorder_value',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Autoimmun Disorder Type'),
        ),
        migrations.AlterField(
            model_name='past_medical_history',
            name='history_of_blood_transfusion_value',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='History Of Blood Transfusion Type'),
        ),
        migrations.AlterField(
            model_name='past_medical_history',
            name='hld_value',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='HLD Type'),
        ),
        migrations.AlterField(
            model_name='past_medical_history',
            name='kidney_disease_value',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Kidney Disease Type'),
        ),
        migrations.AlterField(
            model_name='past_medical_history',
            name='pulmonar',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Pulmonary'),
        ),
        migrations.AlterField(
            model_name='past_medical_history',
            name='thyroid_dysfunction_value',
            field=models.CharField(blank=True, choices=[('hypo', 'HYPO'), ('hyper', 'HYPER')], max_length=20, null=True, verbose_name='THYROID DYSFUNCTION Type'),
        ),
    ]
