# Generated by Django 3.0.1 on 2020-01-21 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_auto_20200121_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='anesthesia_doc',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='دكتور التخدير'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='anesthesia_type',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=50, null=True, verbose_name='نوع التخدير'),
        ),
    ]
