# Generated by Django 2.2 on 2021-03-11 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_auto_20210309_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='barcode_image',
            field=models.ImageField(blank=True, null=True, upload_to='barcode/'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='barcode',
            field=models.CharField(max_length=70, verbose_name='barcode Number'),
        ),
    ]
