# Generated by Django 3.0.1 on 2020-01-21 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_auto_20200121_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='check_up',
            name='exit_desc',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='علي مسئولية من'),
        ),
        migrations.AddField(
            model_name='check_up',
            name='exit_nature',
            field=models.CharField(blank=True, choices=[('better', 'تحسن'), ('responsibility', 'علي مسئولية'), ('scape', 'هروب')], max_length=50, null=True, verbose_name='نوعية الخروج'),
        ),
        migrations.AddField(
            model_name='check_up',
            name='fetal_heart_rate',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='ضربات قلب الجنين'),
        ),
        migrations.AddField(
            model_name='check_up',
            name='fetal_movement',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='حركة الجنين'),
        ),
        migrations.AddField(
            model_name='check_up',
            name='fetal_position',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='وضعية الجنين'),
        ),
        migrations.AddField(
            model_name='check_up',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patient.Patient', verbose_name='المريضة'),
        ),
        migrations.AddField(
            model_name='check_up',
            name='placenta',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='المشيمة'),
        ),
        migrations.AddField(
            model_name='check_up',
            name='surgery',
            field=models.CharField(blank=True, choices=[('curettage_cleaning', 'كحت و تنظيف'), ('cervical_stitch', 'غرزة بعنق الرحم'), ('ectopic_pregnancy', 'حمل خارج الرحم')], max_length=50, null=True, verbose_name='عمليات'),
        ),
        migrations.AddField(
            model_name='check_up',
            name='surgery_desc',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='شرح عمليات'),
        ),
        migrations.AddField(
            model_name='check_up',
            name='water',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='نسبة المياة'),
        ),
        migrations.AlterField(
            model_name='check_up',
            name='hemoglobin',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Hb%'),
        ),
        migrations.AlterField(
            model_name='check_up',
            name='protine',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='البروتين'),
        ),
        migrations.AlterField(
            model_name='check_up',
            name='rbs',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='rbs'),
        ),
        migrations.AlterField(
            model_name='check_up',
            name='weight',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='الوزن'),
        ),
    ]
