# Generated by Django 2.2 on 2021-03-11 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_auto_20210311_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='barcode',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='barcode Number'),
        ),
    ]
