# Generated by Django 3.0.1 on 2020-01-27 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_auto_20200121_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_files',
            name='attachment',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='المرفقات'),
        ),
        migrations.AlterField(
            model_name='patient_files',
            name='attachment_name',
            field=models.CharField(max_length=150, verbose_name='اسم المرفق'),
        ),
    ]
