# Generated by Django 3.0.1 on 2020-02-01 13:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0006_auto_20200127_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='anesthesia_type',
            field=models.CharField(blank=True, choices=[('T', 'Total anesthesia'), ('H', 'Half anesthesia'), ('L', 'Local anesthesia')], max_length=50, null=True, verbose_name='نوع التخدير'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='تاريخ الولادة'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='fetal_sex',
            field=models.CharField(blank=True, choices=[('m', 'ذكر'), ('f', 'انثي'), ('t', 'توأم')], max_length=50, null=True, verbose_name='نوع المولود'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='lnmp',
            field=models.DateField(blank=True, default=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='تاريخ الولادة'), null=True, verbose_name='اخر تاريخ للدورة الشهرية'),
        ),
    ]
