# Generated by Django 2.2 on 2021-03-12 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0006_auto_20210311_1632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient_exit',
            name='date_end',
        ),
        migrations.RemoveField(
            model_name='patient_exit',
            name='date_start',
        ),
    ]
