# Generated by Django 3.0.1 on 2020-02-01 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0008_auto_20200201_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='description',
            field=models.CharField(max_length=250, verbose_name='بيانات عن الحمل'),
        ),
    ]
