# Generated by Django 3.0.1 on 2020-02-02 19:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0009_auto_20200201_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='date',
            field=models.DateField(blank=True, default=datetime.date(2020, 2, 2), null=True, verbose_name='تاريخ الولادة'),
        ),
    ]
