# Generated by Django 3.0.1 on 2020-02-03 20:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0010_auto_20200202_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='date',
            field=models.DateField(blank=True, default=datetime.date(2020, 2, 3), null=True, verbose_name='تاريخ الولادة'),
        ),
    ]
