# Generated by Django 3.0.1 on 2020-02-07 14:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0011_auto_20200203_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='check_up',
            name='week_number',
            field=models.CharField(default=1, max_length=3, verbose_name='اسبوع الحمل'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='check_up',
            name='complain',
            field=models.CharField(max_length=200, verbose_name='المتابعة'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='date',
            field=models.DateField(blank=True, default=datetime.date(2020, 2, 7), null=True, verbose_name='تاريخ الولادة'),
        ),
    ]
