# Generated by Django 3.0.1 on 2020-02-10 10:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
        ('patient', '0012_auto_20200207_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='hospital',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='clinic.Clinic', verbose_name='المستشفي'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='delivery',
            name='date',
            field=models.DateField(blank=True, default=datetime.date(2020, 2, 10), null=True, verbose_name='تاريخ الولادة'),
        ),
    ]
