# Generated by Django 3.0.1 on 2020-02-11 19:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0013_auto_20200210_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='date',
            field=models.DateField(blank=True, default=datetime.date(2020, 2, 11), null=True, verbose_name='تاريخ الولادة'),
        ),
    ]
