# Generated by Django 3.0.1 on 2020-02-12 21:22

import datetime
from django.db import migrations, models
import patient.models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0014_auto_20200211_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='date',
            field=models.DateField(blank=True, default=datetime.date(2020, 2, 12), null=True, verbose_name='تاريخ الولادة'),
        ),
        migrations.AlterField(
            model_name='patient_files',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=patient.models.path_and_rename, verbose_name='المرفقات'),
        ),
    ]
