# Generated by Django 3.0.1 on 2020-02-12 21:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0016_auto_20200212_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='تاريخ الولادة'),
        ),
    ]
