# Generated by Django 3.0.1 on 2020-02-12 21:44

from django.db import migrations, models
import patient.models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0017_auto_20200212_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_files',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=patient.models.path_and_rename, verbose_name='المرفقات'),
        ),
    ]
