# Generated by Django 3.0.1 on 2020-02-12 21:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0018_auto_20200212_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_files',
            name='start_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Start Date'),
        ),
    ]
