# Generated by Django 3.0.1 on 2020-02-15 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0019_auto_20200212_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='notes',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='ملاحظات'),
        ),
        migrations.AddField(
            model_name='patient',
            name='transferred_from',
            field=models.CharField(blank=True, choices=[('insurance', 'عيادة تأمين'), ('consultant', 'عيادة استشاري'), ('outpatient', 'طبيب خارجي'), ('patient', 'المريض نفسه')], max_length=70, null=True, verbose_name='المريضة محولة من'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='description',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='بيانات عن الحمل'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='hospital_section',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='القسم'),
        ),
    ]
