# Generated by Django 3.0.1 on 2020-02-15 09:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0020_auto_20200215_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='check_up',
            name='calcsan_sarf_date',
            field=models.DateField(default=datetime.date.today, verbose_name='تاريخ صرف الكلكسان'),
        ),
        migrations.AddField(
            model_name='patient',
            name='kalksan_order_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم قرار صرف الكلكسان'),
        ),
    ]
