# Generated by Django 3.0.1 on 2020-02-15 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0021_auto_20200215_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='type',
            field=models.CharField(blank=True, choices=[('n', 'طبيعي'), ('c', 'قيصري')], max_length=30, null=True, verbose_name='نوع الولادة'),
        ),
    ]
