# Generated by Django 3.0.1 on 2020-02-15 15:01

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pharmacy', '0002_auto_20200127_1954'),
        ('patient', '0022_auto_20200215_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check_up',
            name='calcsan_sarf_date',
            field=models.DateField(verbose_name='تاريخ صرف الكلكسان'),
        ),
        migrations.CreateModel(
            name='Patient_Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField(default=datetime.date.today, verbose_name='تاريخ الصرف')),
                ('dose', models.PositiveIntegerField(verbose_name='الجرعة')),
                ('notes', models.CharField(blank=True, max_length=250, null=True, verbose_name='ملاحظات')),
                ('creation_date', models.DateField(auto_now=True)),
                ('last_update_date', models.DateField(auto_now_add=True)),
                ('check_up', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.Check_Up', verbose_name='المتابعة')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_med_created_by', to=settings.AUTH_USER_MODEL)),
                ('last_update_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_med_last_updated_by', to=settings.AUTH_USER_MODEL)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.Medicine', verbose_name='الدواء')),
            ],
        ),
    ]
