# Generated by Django 3.0.1 on 2020-02-19 20:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patient', '0023_auto_20200215_1701'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient_Days_Off',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField(verbose_name='تاريخ بداية الاجازة')),
                ('date_end', models.DateField(blank=True, null=True, verbose_name='تاريخ نهاية الاجازة')),
                ('num_of_days', models.PositiveIntegerField()),
                ('creation_date', models.DateField(auto_now=True)),
                ('last_update_date', models.DateField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_day_off_created_by', to=settings.AUTH_USER_MODEL)),
                ('last_update_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_day_off_last_updated_by', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_day_off', to='patient.Patient', verbose_name='المريضة')),
            ],
        ),
    ]
