# Generated by Django 3.0.1 on 2020-02-19 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0024_patient_days_off'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient_days_off',
            name='notes',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='ملاحظات'),
        ),
    ]
