# Generated by Django 3.0.1 on 2020-02-21 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0025_patient_days_off_notes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='check_up',
            old_name='calcsan_sarf_date',
            new_name='clexane_sarf_date',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='kalksan_order_number',
            new_name='clexane_order_number',
        ),
    ]
