# Generated by Django 3.0.1 on 2020-03-02 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0027_auto_20200226_2226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='consultant_flag',
        ),
    ]
