# Generated by Django 3.0.1 on 2020-03-03 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0028_remove_patient_consultant_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='check_up',
            name='allergy_hx',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Allergy Hx'),
        ),
        migrations.AddField(
            model_name='check_up',
            name='mhx',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='MHx'),
        ),
        migrations.AddField(
            model_name='check_up',
            name='shx',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='SHx'),
        ),
        migrations.AddField(
            model_name='check_up',
            name='us',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='US'),
        ),
        migrations.AlterField(
            model_name='check_up',
            name='complain',
            field=models.CharField(max_length=200, verbose_name='شكوي المريضة'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='exit_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ الخروج'),
        ),
    ]
