# Generated by Django 3.0.1 on 2020-03-04 20:15

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patient', '0029_auto_20200303_1109'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ultrasound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prognosis', models.TextField(max_length=250, verbose_name='التشخيص')),
                ('visit_date', models.DateField(default=datetime.date.today, verbose_name='تاريخ الزيارة')),
                ('creation_date', models.DateField(auto_now=True)),
                ('last_update_date', models.DateField(auto_now_add=True)),
                ('check_up', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.Check_Up', verbose_name='المتابعة')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ultrasound_created_by', to=settings.AUTH_USER_MODEL)),
                ('last_update_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ultrasound_last_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
