# Generated by Django 3.0.1 on 2020-03-05 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0030_ultrasound'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='check_up',
            name='us',
        ),
    ]
