# Generated by Django 3.0.1 on 2020-03-07 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0031_remove_check_up_us'),
    ]

    operations = [
        migrations.AddField(
            model_name='check_up',
            name='g',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='G'),
        ),
        migrations.AddField(
            model_name='check_up',
            name='p',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='P'),
        ),
        migrations.AddField(
            model_name='check_up',
            name='pre',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Pre'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='description',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='ملاحظات الولادة'),
        ),
        migrations.AlterField(
            model_name='ultrasound',
            name='check_up',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patient.Check_Up', verbose_name='المتابعة'),
        ),
    ]
