# Generated by Django 3.0.1 on 2020-03-07 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0032_auto_20200307_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check_up',
            name='clexane_sarf_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ صرف الكلكسان'),
        ),
        migrations.AlterField(
            model_name='check_up',
            name='weight',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='وزن الجنين'),
        ),
    ]
