# Generated by Django 3.0.1 on 2020-03-10 14:32

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patient', '0033_auto_20200307_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check_up',
            name='surgery',
            field=models.CharField(blank=True, choices=[('curettage_cleaning', 'كحت و تنظيف'), ('cervical_stitch', 'غرزة بعنق الرحم'), ('ectopic_pregnancy', 'حمل خارج الرحم'), ('CS', 'ولادة قيصري')], max_length=50, null=True, verbose_name='عمليات'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='anesthesia_type',
            field=models.CharField(blank=True, choices=[('S', 'Spinal anesthesia'), ('G', 'General anesthesia')], max_length=50, null=True, verbose_name='نوع التخدير'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_type',
            field=models.CharField(blank=True, choices=[('CHECK_UP', 'متابعة'), ('CONSULTANT', 'استشاري'), ('OPERATION', 'عمليات نسا'), ('DELIVER', 'ولادة')], max_length=50, null=True, verbose_name='طبيعة المريضة'),
        ),
        migrations.CreateModel(
            name='Diabetes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bs', models.PositiveIntegerField(verbose_name='قياس السكر')),
                ('bp', models.TextField(max_length=250, verbose_name='قياس الضغط')),
                ('reading_date', models.DateField(default=datetime.date.today, verbose_name='تاريخ القراءة')),
                ('creation_date', models.DateField(auto_now=True)),
                ('last_update_date', models.DateField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diabetes_created_by', to=settings.AUTH_USER_MODEL)),
                ('last_update_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diabetes_last_updated_by', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_diabetes', to='patient.Patient', verbose_name='المريضة')),
            ],
        ),
    ]
