# Generated by Django 3.0.1 on 2020-03-10 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0034_auto_20200310_1632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='check_up',
            name='delivery',
        ),
    ]
