# Generated by Django 3.0.1 on 2020-03-10 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0035_remove_check_up_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diabetes',
            name='bp',
            field=models.CharField(max_length=10, verbose_name='قياس الضغط'),
        ),
    ]
