# Generated by Django 3.0.1 on 2020-03-10 19:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0036_auto_20200310_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diabetes',
            name='reading_date',
            field=models.DateTimeField(default=datetime.date.today, verbose_name='تاريخ القراءة'),
        ),
    ]
