# Generated by Django 3.0.1 on 2020-03-10 19:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0037_auto_20200310_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='diabetes',
            name='temp',
            field=models.PositiveIntegerField(default=37, verbose_name='درجة الحرارة'),
        ),
        migrations.AlterField(
            model_name='diabetes',
            name='reading_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 10, 21, 35, 37, 943950), verbose_name='تاريخ القراءة'),
        ),
    ]
