# Generated by Django 3.0.1 on 2020-03-13 06:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0038_auto_20200310_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diabetes',
            name='reading_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 13, 8, 56, 51, 989716), verbose_name='تاريخ القراءة'),
        ),
    ]
