# Generated by Django 3.0.1 on 2020-03-13 07:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0040_auto_20200313_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='exit_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ الخروج'),
        ),
        migrations.AddField(
            model_name='patient',
            name='exit_note',
            field=models.TextField(blank=True, max_length=250, null=True, verbose_name='ملاحظات الخروج'),
        ),
        migrations.AlterField(
            model_name='diabetes',
            name='reading_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 13, 9, 49, 22, 217283), verbose_name='تاريخ القراءة'),
        ),
    ]
