# Generated by Django 3.0.1 on 2020-03-18 10:44

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patient', '0046_auto_20200314_1059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='check_up',
            name='g',
        ),
        migrations.RemoveField(
            model_name='check_up',
            name='p',
        ),
        migrations.RemoveField(
            model_name='check_up',
            name='pre',
        ),
        migrations.AddField(
            model_name='patient',
            name='g',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='G'),
        ),
        migrations.AddField(
            model_name='patient',
            name='husband_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='اسم الزوج'),
        ),
        migrations.AddField(
            model_name='patient',
            name='husband_phone',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='هاتف الزوج'),
        ),
        migrations.AddField(
            model_name='patient',
            name='p',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='P'),
        ),
        migrations.AddField(
            model_name='patient',
            name='pre',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Pre'),
        ),
        migrations.AlterField(
            model_name='check_up',
            name='complain',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='شكوي المريضة'),
        ),
        migrations.AlterField(
            model_name='check_up',
            name='hemoglobin',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Hb%'),
        ),
        migrations.AlterField(
            model_name='check_up',
            name='placenta',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='ارتفاع المشيمة'),
        ),
        migrations.AlterField(
            model_name='check_up',
            name='week_number',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='اسبوع الحمل'),
        ),
        migrations.AlterField(
            model_name='check_up',
            name='weight',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='الوزن'),
        ),
        migrations.AlterField(
            model_name='diabetes',
            name='reading_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 18, 12, 44, 18, 625780), verbose_name='تاريخ القراءة'),
        ),
        migrations.CreateModel(
            name='Past_Medical_History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diabetes', models.CharField(blank=True, max_length=255, null=True, verbose_name='diabetes')),
                ('pulmonar', models.CharField(blank=True, max_length=255, null=True, verbose_name='pulmonar')),
                ('hypertension', models.CharField(blank=True, max_length=255, null=True, verbose_name='hypertension')),
                ('allergies', models.CharField(blank=True, max_length=255, null=True, verbose_name='allergies')),
                ('heart_disease', models.CharField(blank=True, max_length=255, null=True, verbose_name='heart_disease')),
                ('breast', models.CharField(blank=True, max_length=255, null=True, verbose_name='breast')),
                ('autoimmun_disorder', models.CharField(blank=True, max_length=255, null=True, verbose_name='autoimmun_disorder')),
                ('abnormal_pap', models.CharField(blank=True, max_length=255, null=True, verbose_name='abnormal_pap')),
                ('kidney_disease', models.CharField(blank=True, max_length=255, null=True, verbose_name='kidney_disease')),
                ('uterine', models.CharField(blank=True, max_length=255, null=True, verbose_name='uterine')),
                ('psychiatric', models.CharField(blank=True, max_length=255, null=True, verbose_name='psychiatric')),
                ('infertility', models.CharField(blank=True, max_length=255, null=True, verbose_name='infertility')),
                ('neurologic', models.CharField(blank=True, max_length=255, null=True, verbose_name='neurologic')),
                ('rfh', models.CharField(blank=True, max_length=255, null=True, verbose_name='rfh')),
                ('hld', models.CharField(blank=True, max_length=255, null=True, verbose_name='hld')),
                ('gyns', models.CharField(blank=True, max_length=255, null=True, verbose_name='gyns')),
                ('varicosities', models.CharField(blank=True, max_length=255, null=True, verbose_name='varicosities')),
                ('operation', models.CharField(blank=True, max_length=255, null=True, verbose_name='operation')),
                ('thyroid_dysfunction', models.CharField(blank=True, max_length=255, null=True, verbose_name='thyroid_dysfunction')),
                ('anesthetic', models.CharField(blank=True, max_length=255, null=True, verbose_name='anesthetic')),
                ('trauma', models.CharField(blank=True, max_length=255, null=True, verbose_name='trauma')),
                ('hobt', models.CharField(blank=True, max_length=255, null=True, verbose_name='hobt')),
                ('othrt', models.CharField(blank=True, max_length=255, null=True, verbose_name='othrt')),
                ('creation_date', models.DateField(auto_now=True)),
                ('last_update_date', models.DateField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_history_created_by', to=settings.AUTH_USER_MODEL)),
                ('last_update_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_history_last_updated_by', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patient.Patient')),
            ],
        ),
    ]
