# Generated by Django 3.0.1 on 2020-03-19 08:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0047_auto_20200318_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diabetes',
            name='reading_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 19, 10, 2, 9, 143721), verbose_name='تاريخ القراءة'),
        ),
        migrations.AlterField(
            model_name='past_medical_history',
            name='patient',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patient.Patient'),
        ),
    ]
