# Generated by Django 3.0.1 on 2020-03-19 12:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0050_auto_20200319_1205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diabetes',
            name='bp',
        ),
        migrations.AddField(
            model_name='diabetes',
            name='bp_down',
            field=models.CharField(default=80, max_length=3, verbose_name='BP Down'),
        ),
        migrations.AddField(
            model_name='diabetes',
            name='bp_up',
            field=models.CharField(default=120, max_length=3, verbose_name='BP Up'),
        ),
        migrations.AlterField(
            model_name='diabetes',
            name='reading_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 19, 14, 26, 10, 715648), verbose_name='تاريخ القراءة'),
        ),
        migrations.AlterField(
            model_name='past_medical_history',
            name='othr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='other'),
        ),
    ]
