# Generated by Django 3.0.1 on 2020-11-06 15:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_auto_20200127_1954'),
        ('patient', '0053_auto_20201106_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check_up',
            name='blood_presure',
            field=models.CharField(default='120/80', max_length=6, verbose_name='Blood presure'),
        ),
        migrations.AlterField(
            model_name='check_up',
            name='clexane_sarf_date',
            field=models.DateField(blank=True, null=True, verbose_name='Clexane sarf date'),
        ),
        migrations.AlterField(
            model_name='check_up',
            name='complain',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Complain'),
        ),
        migrations.AlterField(
            model_name='check_up',
            name='exit_desc',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Responsibility'),
        ),
        migrations.AlterField(
            model_name='check_up',
            name='exit_nature',
            field=models.CharField(blank=True, choices=[('better', 'Better'), ('responsibility', 'Responsibility'), ('scape', 'Scape')], max_length=50, null=True, verbose_name='Exit Nature'),
        ),
        migrations.AlterField(
            model_name='check_up',
            name='fetal_heart_rate',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Fetal heart rate'),
        ),
        migrations.AlterField(
            model_name='check_up',
            name='fetal_movement',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Fetal movement'),
        ),
        migrations.AlterField(
            model_name='check_up',
            name='fetal_position',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Fetal position'),
        ),
        migrations.AlterField(
            model_name='check_up',
            name='hemoglobin',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='HB%'),
        ),
        migrations.AlterField(
            model_name='check_up',
            name='next_visit',
            field=models.DateField(blank=True, null=True, verbose_name='Next visit date'),
        ),
        migrations.AlterField(
            model_name='check_up',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patient.Patient', verbose_name='Patient'),
        ),
        migrations.AlterField(
            model_name='check_up',
            name='placenta',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Placenta'),
        ),
        migrations.AlterField(
            model_name='check_up',
            name='protine',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Protine'),
        ),
        migrations.AlterField(
            model_name='check_up',
            name='rbs',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='RBS'),
        ),
        migrations.AlterField(
            model_name='check_up',
            name='surgery',
            field=models.CharField(blank=True, choices=[('curettage_cleaning', 'كحت و تنظيف'), ('cervical_stitch', 'غرزة بعنق الرحم'), ('ectopic_pregnancy', 'حمل خارج الرحم'), ('CS', 'ولادة قيصري')], max_length=50, null=True, verbose_name='Surgery'),
        ),
        migrations.AlterField(
            model_name='check_up',
            name='surgery_desc',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Surgery desc'),
        ),
        migrations.AlterField(
            model_name='check_up',
            name='visit_date',
            field=models.DateField(blank=True, null=True, verbose_name='Visit date'),
        ),
        migrations.AlterField(
            model_name='check_up',
            name='water',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Water'),
        ),
        migrations.AlterField(
            model_name='check_up',
            name='week_number',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Week Number'),
        ),
        migrations.AlterField(
            model_name='check_up',
            name='weight',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Weight'),
        ),
        migrations.AlterField(
            model_name='diabetes',
            name='bs',
            field=models.PositiveIntegerField(verbose_name='Blood sugar'),
        ),
        migrations.AlterField(
            model_name='diabetes',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_diabetes', to='patient.Patient', verbose_name='Patient'),
        ),
        migrations.AlterField(
            model_name='diabetes',
            name='reading_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 6, 17, 12, 36, 960449), verbose_name='reading date'),
        ),
        migrations.AlterField(
            model_name='diabetes',
            name='temp',
            field=models.PositiveIntegerField(default=37, verbose_name='Temprature'),
        ),
        migrations.AlterField(
            model_name='gynecology',
            name='diagnosis_ar',
            field=models.CharField(max_length=200, verbose_name='Diagnosis AR'),
        ),
        migrations.AlterField(
            model_name='gynecology',
            name='diagnosis_en',
            field=models.CharField(max_length=200, verbose_name='Diagnosis EN'),
        ),
        migrations.AlterField(
            model_name='patient_days_off',
            name='date_end',
            field=models.DateField(blank=True, null=True, verbose_name='Days-off End Date'),
        ),
        migrations.AlterField(
            model_name='patient_days_off',
            name='date_start',
            field=models.DateField(verbose_name='Days-off Start Date'),
        ),
        migrations.AlterField(
            model_name='patient_days_off',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_day_off', to='patient.Patient', verbose_name='Patient'),
        ),
        migrations.AlterField(
            model_name='patient_medicine',
            name='check_up',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.Check_Up', verbose_name='Follow up'),
        ),
        migrations.AlterField(
            model_name='patient_medicine',
            name='dose',
            field=models.PositiveIntegerField(verbose_name='Dose'),
        ),
        migrations.AlterField(
            model_name='patient_medicine',
            name='issue_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Issue date'),
        ),
        migrations.AlterField(
            model_name='patient_medicine',
            name='medicine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.Medicine', verbose_name='Medicine'),
        ),
        migrations.AlterField(
            model_name='patient_medicine',
            name='notes',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='ultrasound',
            name='check_up',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patient.Check_Up', verbose_name='Follow up'),
        ),
        migrations.AlterField(
            model_name='ultrasound',
            name='prognosis',
            field=models.TextField(max_length=250, verbose_name='Prognosis'),
        ),
        migrations.AlterField(
            model_name='ultrasound',
            name='visit_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Visit date'),
        ),
    ]
