# Generated by Django 3.0.1 on 2020-11-15 09:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0055_auto_20201115_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diabetes',
            name='reading_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 15, 11, 53, 40, 911513), verbose_name='reading date'),
        ),
    ]
